<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('municipios')->insert([
            ['id' => '1', 'name' => 'Chahal', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2', 'name' => 'Chisec', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3', 'name' => 'Cobán', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '4', 'name' => 'Fray Bartolomé de las Casas', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5', 'name' => 'La Tinta', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6', 'name' => 'Lanquín', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7', 'name' => 'Panzós', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8', 'name' => 'Raxruhá', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9', 'name' => 'San Cristóbal Verapaz', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '10', 'name' => 'San Juan Chamelco', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '11', 'name' => 'San Pedro Carchá', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '12', 'name' => 'Santa Cruz Verapaz', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '13', 'name' => 'Santa María Cahabón', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '14', 'name' => 'Senahú', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '15', 'name' => 'Tamahú', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '16', 'name' => 'Tactic', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '17', 'name' => 'Tucurú', 'departamento_id' => 1, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '18', 'name' => 'Cubulco', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '19', 'name' => 'Granados', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '20', 'name' => 'Purulhá', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '21', 'name' => 'Rabinal', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '22', 'name' => 'Salamá', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '23', 'name' => 'San Jerónimo', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '24', 'name' => 'San Miguel Chicaj', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '25', 'name' => 'Santa Cruz el Chol', 'departamento_id' => 2, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '26', 'name' => 'Acatenango', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '27', 'name' => 'Chimaltenango', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '28', 'name' => 'El Tejar', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '29', 'name' => 'Parramos', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '30', 'name' => 'Patzicía', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '31', 'name' => 'Patzún', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '32', 'name' => 'Pochuta', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '33', 'name' => 'San Andrés Itzapa', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '34', 'name' => 'San José Poaquíl', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '35', 'name' => 'San Juan Comalapa', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '36', 'name' => 'San Martín Jilotepeque', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '37', 'name' => 'Santa Apolonia', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '38', 'name' => 'Santa Cruz Balanyá', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '39', 'name' => 'Tecpán', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '40', 'name' => 'Yepocapa', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '41', 'name' => 'Zaragoza', 'departamento_id' => 3, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '42', 'name' => 'Camotán', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '43', 'name' => 'Chiquimula', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '44', 'name' => 'Concepción Las Minas', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '45', 'name' => 'Esquipulas', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '46', 'name' => 'Ipala', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '47', 'name' => 'Jocotán', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '48', 'name' => 'Olopa', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '49', 'name' => 'Quezaltepeque', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '50', 'name' => 'San Jacinto', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '51', 'name' => 'San José la Arada', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '52', 'name' => 'San Juan Ermita', 'departamento_id' => 4, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '53', 'name' => 'El Jícaro', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '54', 'name' => 'Guastatoya', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '55', 'name' => 'Morazán', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '56', 'name' => 'San Agustín Acasaguastlán', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '57', 'name' => 'San Antonio La Paz', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '58', 'name' => 'San Cristóbal Acasaguastlán', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '59', 'name' => 'Sanarate', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '60', 'name' => 'Sansare', 'departamento_id' => 5, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '61', 'name' => 'Escuintla', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '62', 'name' => 'Guanagazapa', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '63', 'name' => 'Iztapa', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '64', 'name' => 'La Democracia', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '65', 'name' => 'La Gomera', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '66', 'name' => 'Masagua', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '67', 'name' => 'Nueva Concepción', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '68', 'name' => 'Palín', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '69', 'name' => 'San José', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '70', 'name' => 'San Vicente Pacaya', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '71', 'name' => 'Santa Lucía Cotzumalguapa', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '72', 'name' => 'Siquinalá', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '73', 'name' => 'Tiquisate', 'departamento_id' => 6, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '74', 'name' => 'Amatitlán', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '75', 'name' => 'Chinautla', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '76', 'name' => 'Chuarrancho', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '77', 'name' => 'Guatemala', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '78', 'name' => 'Fraijanes', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '79', 'name' => 'Mixco', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '80', 'name' => 'Palencia', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '81', 'name' => 'San José del Golfo', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '82', 'name' => 'San José Pinula', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '83', 'name' => 'San Juan Sacatepéquez', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '84', 'name' => 'San Miguel Petapa', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '85', 'name' => 'San Pedro Ayampuc', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '86', 'name' => 'San Pedro Sacatepéquez', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '87', 'name' => 'San Raymundo', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '88', 'name' => 'Santa Catarina Pinula', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '89', 'name' => 'Villa Canales', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '90', 'name' => 'Villa Nueva', 'departamento_id' => 7, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '91', 'name' => 'Aguacatán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '92', 'name' => 'Chiantla', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '93', 'name' => 'Colotenango', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '94', 'name' => 'Concepción Huista', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '95', 'name' => 'Cuilco', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '96', 'name' => 'Huehuetenango', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '97', 'name' => 'Jacaltenango', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '98', 'name' => 'La Democracia', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '99', 'name' => 'La Libertad', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '100', 'name' => 'Malacatancito', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '101', 'name' => 'Nentón', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '102', 'name' => 'San Antonio Huista', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '103', 'name' => 'San Gaspar Ixchil', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '104', 'name' => 'San Ildefonso Ixtahuacán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '105', 'name' => 'San Juan Atitán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '106', 'name' => 'San Juan Ixcoy', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '107', 'name' => 'San Mateo Ixtatán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '108', 'name' => 'San Miguel Acatán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '109', 'name' => 'San Pedro Nécta', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '110', 'name' => 'San Pedro Soloma', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '111', 'name' => 'San Rafael La Independencia', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '112', 'name' => 'San Rafael Pétzal', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '113', 'name' => 'San Sebastián Coatán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '114', 'name' => 'San Sebastián Huehuetenango', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '115', 'name' => 'Santa Ana Huista', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '116', 'name' => 'Santa Bárbara', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '117', 'name' => 'Santa Cruz Barillas', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '118', 'name' => 'Santa Eulalia', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '119', 'name' => 'Santiago Chimaltenango', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '120', 'name' => 'Tectitán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '121', 'name' => 'Todos Santos Cuchumatán', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '122', 'name' => 'Unión Cantinil', 'departamento_id' => 8, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '123', 'name' => 'El Estor', 'departamento_id' => 9, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '124', 'name' => 'Livingston', 'departamento_id' => 9, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '125', 'name' => 'Los Amates', 'departamento_id' => 9, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '126', 'name' => 'Morales', 'departamento_id' => 9, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '127', 'name' => 'Puerto Barrios', 'departamento_id' => 9, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '128', 'name' => 'Jalapa', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '129', 'name' => 'Mataquescuintla', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '130', 'name' => 'Monjas', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '131', 'name' => 'San Carlos Alzatate', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '132', 'name' => 'San Luis Jilotepeque', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '133', 'name' => 'San Manuel Chaparrón', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '134', 'name' => 'San Pedro Pinula', 'departamento_id' => 10, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '135', 'name' => 'Agua Blanca', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '136', 'name' => 'Asunción Mita', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '137', 'name' => 'Atescatempa', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '138', 'name' => 'Comapa', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '139', 'name' => 'Conguaco', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '140', 'name' => 'El Adelanto', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '141', 'name' => 'El Progreso', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '142', 'name' => 'Jalpatagua', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '143', 'name' => 'Jerez', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '144', 'name' => 'Jutiapa', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '145', 'name' => 'Moyuta', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '146', 'name' => 'Pasaco', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '147', 'name' => 'Quesada', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '148', 'name' => 'San José Acatempa', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '149', 'name' => 'Santa Catarina Mita', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '150', 'name' => 'Yupiltepeque', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '151', 'name' => 'Zapotitlán', 'departamento_id' => 11, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '152', 'name' => 'Dolores', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '153', 'name' => 'El Chal', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '154', 'name' => 'Ciudad Flores', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '155', 'name' => 'La Libertad', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '156', 'name' => 'Las Cruces', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '157', 'name' => 'Melchor de Mencos', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '158', 'name' => 'Poptún', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '159', 'name' => 'San Andrés', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '160', 'name' => 'San Benito', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '161', 'name' => 'San Francisco', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '162', 'name' => 'San José', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '163', 'name' => 'San Luis', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '164', 'name' => 'Santa Ana', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '165', 'name' => 'Sayaxché', 'departamento_id' => 12, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '166', 'name' => 'Almolonga', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '167', 'name' => 'Cabricán', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '168', 'name' => 'Cajolá', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '169', 'name' => 'Cantel', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '170', 'name' => 'Coatepeque', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '171', 'name' => 'Colomba Costa Cuca', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '172', 'name' => 'Concepción Chiquirichapa', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '173', 'name' => 'El Palmar', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '174', 'name' => 'Flores Costa Cuca', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '175', 'name' => 'Génova', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '176', 'name' => 'Huitán', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '177', 'name' => 'La Esperanza', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '178', 'name' => 'Olintepeque', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '179', 'name' => 'Palestina de Los Altos', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '180', 'name' => 'Quetzaltenango', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '181', 'name' => 'Salcajá', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '182', 'name' => 'San Carlos Sija', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '183', 'name' => 'San Francisco La Unión', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '184', 'name' => 'San Juan Ostuncalco', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '185', 'name' => 'San Martín Sacatepéquez', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '186', 'name' => 'San Mateo', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '187', 'name' => 'San Miguel Sigüilá', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '188', 'name' => 'Sibilia', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '189', 'name' => 'Zunil', 'departamento_id' => 13, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '190', 'name' => 'Canillá', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '191', 'name' => 'Chajul', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '192', 'name' => 'Chicamán', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '193', 'name' => 'Chiché', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '194', 'name' => 'Chichicastenango', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '195', 'name' => 'Chinique', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '196', 'name' => 'Cunén', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '197', 'name' => 'Ixcán Playa Grande', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '198', 'name' => 'Joyabaj', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '199', 'name' => 'Nebaj', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '200', 'name' => 'Pachalum', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '201', 'name' => 'Patzité', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '202', 'name' => 'Sacapulas', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '203', 'name' => 'San Andrés Sajcabajá', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '204', 'name' => 'San Antonio Ilotenango', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '205', 'name' => 'San Bartolomé Jocotenango', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '206', 'name' => 'San Juan Cotzal', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '207', 'name' => 'San Pedro Jocopilas', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '208', 'name' => 'Santa Cruz del Quiché', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '209', 'name' => 'Uspantán', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '210', 'name' => 'Zacualpa', 'departamento_id' => 14, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '211', 'name' => 'Champerico', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '212', 'name' => 'El Asintal', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '213', 'name' => 'Nuevo San Carlos', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '214', 'name' => 'Retalhuleu', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '215', 'name' => 'San Andrés Villa Seca', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '216', 'name' => 'San Felipe Reu', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '217', 'name' => 'San Martín Zapotitlán', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '218', 'name' => 'San Sebastián', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '219', 'name' => 'Santa Cruz Muluá', 'departamento_id' => 15, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '220', 'name' => 'Alotenango', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '221', 'name' => 'Ciudad Vieja', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '222', 'name' => 'Jocotenango', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '223', 'name' => 'Antigua Guatemala', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '224', 'name' => 'Magdalena Milpas Altas', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '225', 'name' => 'Pastores', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '226', 'name' => 'San Antonio Aguas Calientes', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '227', 'name' => 'San Bartolomé Milpas Altas', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '228', 'name' => 'San Lucas Sacatepéquez', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '229', 'name' => 'San Miguel Dueñas', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '230', 'name' => 'Santa Catarina Barahona', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '231', 'name' => 'Santa Lucía Milpas Altas', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '232', 'name' => 'Santa María de Jesús', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '233', 'name' => 'Santiago Sacatepéquez', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '234', 'name' => 'Santo Domingo Xenacoj', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '235', 'name' => 'Sumpango', 'departamento_id' => 16, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '236', 'name' => 'Ayutla', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '237', 'name' => 'Catarina', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '238', 'name' => 'Comitancillo', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '239', 'name' => 'Concepción Tutuapa', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '240', 'name' => 'El Quetzal', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '241', 'name' => 'El Tumbador', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '242', 'name' => 'Esquipulas Palo Gordo', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '243', 'name' => 'Ixchiguán', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '244', 'name' => 'La Blanca', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '245', 'name' => 'La Reforma', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '246', 'name' => 'Malacatán', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '247', 'name' => 'Nuevo Progreso', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '248', 'name' => 'Ocós', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '249', 'name' => 'Pajapita', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '250', 'name' => 'Río Blanco', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '251', 'name' => 'San Antonio Sacatepéquez', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '252', 'name' => 'San Cristóbal Cucho', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '253', 'name' => 'San José El Rodeo', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '254', 'name' => 'San José Ojetenam', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '255', 'name' => 'San Lorenzo', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '256', 'name' => 'San Marcos', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '257', 'name' => 'San Miguel Ixtahuacán', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '258', 'name' => 'San Pablo', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '259', 'name' => 'San Pedro Sacatepéquez', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '260', 'name' => 'San Rafael Pie de la Cuesta', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '261', 'name' => 'Sibinal', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '262', 'name' => 'Sipacapa', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '263', 'name' => 'Tacaná', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '264', 'name' => 'Tajumulco', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '265', 'name' => 'Tejutla', 'departamento_id' => 17, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '266', 'name' => 'Barberena', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '267', 'name' => 'Casillas', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '268', 'name' => 'Chiquimulilla', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '269', 'name' => 'Cuilapa', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '270', 'name' => 'Guazacapán', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '271', 'name' => 'Nueva Santa Rosa', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '272', 'name' => 'Oratorio', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '273', 'name' => 'Pueblo Nuevo Viñas', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '274', 'name' => 'San Juan Tecuaco', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '275', 'name' => 'San Rafael las Flores', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '276', 'name' => 'Santa Cruz Naranjo', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '277', 'name' => 'Santa María Ixhuatán', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '278', 'name' => 'Santa Rosa de Lima', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '279', 'name' => 'Taxisco', 'departamento_id' => 18, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '280', 'name' => 'Concepción', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '281', 'name' => 'Nahualá', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '282', 'name' => 'Panajachel', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '283', 'name' => 'San Andrés Semetabaj', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '284', 'name' => 'San Antonio Palopó', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '285', 'name' => 'San José Chacayá', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '286', 'name' => 'San Juan La Laguna', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '287', 'name' => 'San Lucas Tolimán', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '288', 'name' => 'San Marcos La Laguna', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '289', 'name' => 'San Pablo La Laguna', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '290', 'name' => 'San Pedro La Laguna', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '291', 'name' => 'Santa Catarina Ixtahuacán', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '292', 'name' => 'Santa Catarina Palopó', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '293', 'name' => 'Santa Clara La Laguna', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '294', 'name' => 'Santa Cruz La Laguna', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '295', 'name' => 'Santa Lucía Utatlán', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '296', 'name' => 'Santa María Visitación', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '297', 'name' => 'Santiago Atitlán', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '298', 'name' => 'Sololá', 'departamento_id' => 19, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '299', 'name' => 'Chicacao', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '300', 'name' => 'Cuyotenango', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '301', 'name' => 'Mazatenango', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '302', 'name' => 'Patulul', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '303', 'name' => 'Pueblo Nuevo', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '304', 'name' => 'Río Bravo', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '305', 'name' => 'Samayac', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '306', 'name' => 'San Antonio Suchitepéquez', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '307', 'name' => 'San Bernardino', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '308', 'name' => 'San Francisco Zapotitlán', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '309', 'name' => 'San Gabriel', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '310', 'name' => 'San José El Idolo', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '311', 'name' => 'San José La Maquina', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '312', 'name' => 'San Juan Bautista', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '313', 'name' => 'San Lorenzo', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '314', 'name' => 'San Miguel Panán', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '315', 'name' => 'San Pablo Jocopilas', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '316', 'name' => 'Santa Bárbara', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '317', 'name' => 'Santo Domingo Suchitepéquez', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '318', 'name' => 'Santo Tomás La Unión', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '319', 'name' => 'Zunilito', 'departamento_id' => 20, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '320', 'name' => 'Momostenango', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '321', 'name' => 'San Andrés Xecul', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '322', 'name' => 'San Bartolo', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '323', 'name' => 'San Cristóbal Totonicapán', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '324', 'name' => 'San Francisco El Alto', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '325', 'name' => 'Santa Lucía La Reforma', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '326', 'name' => 'Santa María Chiquimula', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '327', 'name' => 'Totonicapán', 'departamento_id' => 21, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '328', 'name' => 'Cabañas', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '329', 'name' => 'Estanzuela', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '330', 'name' => 'Gualán', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '331', 'name' => 'Huité', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '332', 'name' => 'La Unión', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '333', 'name' => 'Río Hondo', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '334', 'name' => 'San Diego', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '335', 'name' => 'San Jorge', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '336', 'name' => 'Teculután', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '337', 'name' => 'Usumatlán', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '338', 'name' => 'Zacapa', 'departamento_id' => 22, 'status' => 1, 'created_at' => now(), 'updated_at' => now()]
        ]);
    }
}
